-- Insert activities for Trip 44444444-4444-4444-4444-444444444444 (美國行)
-- Date: 2026-04-30

INSERT INTO activities (
    id, trip_id, time, title, subtitle, content, type, icon_name, personal_info, sort_order, location_name, latitude, longitude, image_urls, created_at, updated_at
) VALUES 
(
    gen_random_uuid(), 
    '44444444-4444-4444-4444-444444444444', 
    '06:30', 
    '晨光攝影：好萊塢標誌最佳取景點', 
    'Lake Hollywood Park', 
    '開啟洛杉磯之晨的最佳方式。Lake Hollywood Park 是拍攝 Hollywood Sign 最完美的角度。標誌就在正前方的山坡上，完全無遮蔽。建議沿著 Canyon Lake Drive 稍微往上走 5 分鐘，可以拍到標誌與下方住宅區交織的層次感。', 
    'TRANSPORT', 
    'camera', 
    '{"photo_spots": ["Grassy Meadow Center", "Upper Dirt Path Viewpoint"]}', 
    1, 
    'Lake Hollywood Park', 
    34.1266, 
    -118.3265, 
    '["https://images.unsplash.com/photo-1444723121867-7a241cacace9"]',
    NOW(),
    NOW()
),
(
    gen_random_uuid(), 
    '44444444-4444-4444-4444-444444444444', 
    '07:30', 
    '抵達環球影城：VIP 極致尊榮體驗', 
    'Universal Studios Hollywood VIP Experience', 
    '抵達後由 VIP 專屬入口進入。您的 VIP 憑證代表園區內最高權限：\n1. 無限次數快速通關 (Unlimited Express Unlimited)\n2. 深度片場導覽 (Exclusive Backlot Access)：允許下車走進正在拍攝中的攝影棚或經典場景（如《驚魂記》貝茲旅館）。\n3. 專家導覽：由專業嚮導引導，免排隊進入所有設施。', 
    'ATTRACTION', 
    'star', 
    '{"ticket_type": "VIP Experience", "benefits": ["Unlimited Express", "Private Tour", "Gourmet Meals"]}', 
    2, 
    'Universal Studios Hollywood', 
    34.1381, 
    -118.3534, 
    '["https://www.universalstudioshollywood.com/static-assets/images/vip-entrance.jpg"]',
    NOW(),
    NOW()
),
(
    gen_random_uuid(), 
    '44444444-4444-4444-4444-444444444444', 
    '09:30', 
    'VIP 專屬私廚午餐與貴賓室', 
    'VIP Private Dining Room', 
    '在避開人潮的專屬餐廳享用由主廚準備的精緻自助饗宴。包含多樣化的冷熱食、新鮮海鮮、精品甜點。VIP 休息室全天候提供無限量的精品咖啡、點心與氣泡水，是旅途中完美的避風港。', 
    'FOOD', 
    'utensils', 
    '{"menu_highlights": ["Gourmet Buffet", "Unlimited Refreshments", "Private Chef"]}', 
    3, 
    'VIP Lounge', 
    NULL, 
    NULL, 
    '["https://www.universalstudioshollywood.com/static-assets/images/vip-dining.jpg"]',
    NOW(),
    NOW()
),
(
    gen_random_uuid(), 
    '44444444-4444-4444-4444-444444444444', 
    'All Day', 
    '環球影城全攻略：任天堂與魔法世界', 
    'Travel Manual: Super Nintendo World & Wizarding World', 
    '【超級任天堂世界】\n- 設施：瑪利歐賽車～庫巴的挑戰書。戴上 AR 護目鏡，這是一場結合現實與擴增實境的比賽。\n- 必吃：Toadstool Cafe 的瑪利歐漢堡、問號塊提拉米蘇。\n- 必買：能量提升手環 (Power-Up Band)，敲擊問號磚塊獲得金幣。\n\n【哈利波特的魔法世界】\n- 設施：禁忌之旅。與哈利一同飛過魁地奇球場。\n- 互動：選購互動魔杖，在活米村櫥窗揮動魔杖施展真實咒語。\n- 必喝：奶油啤酒 (Butterbeer)，推薦 Frozen 口感更細緻。\n\n【其他推薦】\n- 下層園區：侏羅紀世界、變形金剛、神鬼傳奇。\n- 必買：小小兵爆米花桶、辛普森巨大粉紅甜甜圈。', 
    'ATTRACTION', 
    'book-open', 
    '{"must_eat": ["Butterbeer", "Mario Burger", "Tiramisu"], "must_buy": ["Power-Up Band", "Interactive Wand"]}', 
    4, 
    'Universal Studios Areas', 
    NULL, 
    NULL, 
    '["https://www.universalstudioshollywood.com/static-assets/images/nintendo-world.jpg"]',
    NOW(),
    NOW()
),
(
    gen_random_uuid(), 
    '44444444-4444-4444-4444-444444444444', 
    '18:00', 
    'CityWalk 霓虹之夜與逛街購物', 
    'Universal CityWalk Hollywood', 
    '園區閉園後，前往外面的 CityWalk。這裡是美食與街頭藝術的集散地。\n- 必吃：Voodoo Doughnut 怪奇甜點（培根楓糖口味）。\n- 必逛：IT''SUGAR 巨型糖果店、NBA Store、LINE FRIENDS。\n- 體驗：The Toothsome Chocolate Emporium 的浮誇奶昔與巧克力餐點。', 
    'ATTRACTION', 
    'shopping-bag', 
    '{"recommendations": ["Voodoo Doughnut", "Toothsome Milkshakes", "IT''SUGAR"]}', 
    5, 
    'Universal CityWalk', 
    34.1365, 
    -118.3532, 
    '["https://www.universalstudioshollywood.com/static-assets/images/citywalk-night.jpg"]',
    NOW(),
    NOW()
);
